version: '3'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - dbdata:/var/lib/mongodb/data
      - ${SEED_FILE_PATH}:/docker-entrypoint-initdb.d/:ro
volumes:
  dbdata:
